### ISSUE TITLE
Option to use the PUT request to update a campaign

### ISSUE THREAD

**Issue by INLOY** [twitterdev/twitter-python-ads-sdk#121]
I didn't find the way to use the PUT request to update the budget of a campaign or to pause a campaign.

**Comment by juanshishido** [comment]
Thanks for the question, @INLOY.

The [`save`](https://github.com/twitterdev/twitter-python-ads-sdk/blob/master/twitter_ads/resource.py#L186-L202) method *either* creates or updates based on presence of an entity ID.

For example, I can load campaign `9hcjp`:

```
# load
>>> campaign = Campaign(account).load(account, "9hcjp")
# retrieve `name` attribute
>>> campaign.name
'test-emoji-targeting'
```

I then change the `name` value:

```
>>> campaign.name = 'test-emoji-targeting-updated-using-sdk'
```

Finally, I save, which *updates* the campaign given the presence of the campaign ID, `9hcjp`:

```
>>> campaign.save()
<Campaign resource at 0x10c338490 id=9hcjp>
# check attributes
>>> campaign.name
'test-emoji-targeting-updated-using-sdk'
>>> campaign.created_at
'2017-09-13T21:36:14Z'
>>> campaign.updated_at
'2017-11-10T03:50:21Z'
```

Hope this helps! In the future, feel free to visit our [developer forums](https://twittercommunity.com/c/advertiser-api). Thanks!
