### ISSUE TITLE
Not Able to Specify a Date when calling for a LineItem report

### ISSUE THREAD

**Issue by KathyShen** [twitterdev/twitter-python-ads-sdk#150]
def main(ACCOUNT_ID, ACCOUNT_NAME):

	# initialize the client
	client = Client(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
	# load the advertiser account instance
	account = client.accounts(ACCOUNT_ID)
	# define metric groups to pull
	metric_groups = [METRIC_GROUP.ENGAGEMENT, METRIC_GROUP.BILLING, METRIC_GROUP.VIDEO, METRIC_GROUP.WEB_CONVERSION, METRIC_GROUP.MOBILE_CONVERSION]

	# initialize list of active line item ids, groups of 20
	batch_list = batch(account.line_items(), account.campaigns())
	# initialize list to hold csv rows
	rows = []

	# Async jobs can only take max 20 line items to fetch stats for, so do multiple requests with groups of 20
	for line_item_batch in batch_list:
		# Send POST request with account id, line item ids to fetch, metrics to fetch, on daily level granularity
		# Editional parameters can be added after **{granularity'}. See queue_async_stats_job() in resource.py
		job = LineItem.queue_async_stats_job(account, line_item_batch.keys(), metric_groups, **{'granularity':'DAY'}) #'start_time': '20180201', 'end_time': '20180301'})

**Comment by KathyShen** [comment]
I tried to use this command 

job = LineItem.queue_async_stats_job(account, line_item_batch.keys(), metric_groups, **{'granularity':'DAY','start_time': '20180201', 'end_time': '20180301'}) 

Then it won't work. Why?

How should I specify a date range and also extract data at daily granularity?

**Comment by erykml** [comment]
Try this:
```
from datetime import datetime 
datetime.datetime.strptime('2018-02-01T00:00:00Z', "%Y-%m-%dT%H:%M:%SZ")
```
