### ISSUE TITLE
Plans to upgrade to version 4

### ISSUE THREAD

**Issue by polakluk** [twitterdev/twitter-python-ads-sdk#171]
Hi everyone,

we were wondering what are the plans for supporting Twitter Ads API version 4? Based on [this document](https://twittercommunity.com/t/ads-api-version-4/111829), Twitter will drop support for version 3 on Feb28 2019.

Cheers!

**Comment by raffclar** [comment]
Looks like they're working on it:
https://github.com/twitterdev/twitter-python-ads-sdk/tree/tbhushan/api_v4

**Comment by smaeda-ks** [comment]
https://github.com/twitterdev/twitter-python-ads-sdk/pull/174

Closing this.
