### ISSUE TITLE
HTTP 411 (Length Required) when uploading an audience csv via the TON endpoint.

### ISSUE THREAD

**Issue by kavdev** [twitterdev/twitter-python-ads-sdk#173]
Hi there!

I'm using the following code to upload a list of users to update CRM lists:

```python
# ...
remote_audience = account.tailored_audiences(id=encoded_remote_audience_id)

with NamedTemporaryFile(mode="w") as new_audience_csv_file:
    new_audience_csv_file.write("\n".join(emails_to_add))
    remote_audience.update(
        file_path=new_audience_csv_file.name,
        list_type=TA_LIST_TYPES.EMAIL,
        operation=TA_OPERATIONS.ADD
    )
```

Twitter is sending back a 411. Am I doing something incorrectly? Should I be using a different write mode? Should I be seeking back to 0 before sending the filename through?

See also:
[KeyError Fix PR](https://github.com/twitterdev/twitter-python-ads-sdk/pull/172)
[Documentation that's missing 411... is this a twitter backend issue?](https://developer.twitter.com/en/docs/ads/general/guides/response-codes.html)

**Comment by smaeda-ks** [comment]
Closing this as we do not support this endpoint anymore.
