### ISSUE TITLE
Twitter Ads API - Get fields for audience

### ISSUE THREAD

**Issue by sudhanshu88241** [twitterdev/twitter-python-ads-sdk#175]
Hi,

I was trying to fetch fields like clicks, impressions, Spend/Cost etc. for each audience id from Twitter API. I tried several endpoints but not able to get the required data.Also, Is this possible to fetch these fields for audiences.

Regards,
Sudhanshu

**Comment by smaeda-ks** [comment]
duplicate: https://twittercommunity.com/t/twitter-ads-api-fetch-impressions-and-enggagements-at-audience-level/121094

Closing this.
