### ISSUE TITLE
Fetch Audience data for individual account_ids

### ISSUE THREAD

**Issue by sshriv14** [twitterdev/twitter-python-ads-sdk#178]
Hi,

Is it possible to get audience related data for custom audience corresponding to each audience_id within and account.If so, please share resource or reference.

Also, If it's not possible then is there any alternate way to do the same.

Regards,
Sudhanshu

**Comment by smaeda-ks** [comment]
@sshriv14 

What kind of data you're looking for? For instance, we have these endpoints:

- [GET accounts/:account_id/tailored_audiences](https://developer.twitter.com/en/docs/ads/audiences/api-reference/tailored-audiences#get-accounts-account-id-tailored-audiences)
- [GET accounts/:account_id/tailored_audiences/:tailored_audience_id](https://developer.twitter.com/en/docs/ads/audiences/api-reference/tailored-audiences#get-accounts-account-id-tailored-audiences-tailored-audience-id)

and it's possible to do the same using this SDK.
