### ISSUE TITLE
Support for Python 3.6+

### ISSUE THREAD

**Issue by itaya-im** [twitterdev/twitter-python-ads-sdk#185]
Tested Python versions are 2.7, 3.3, 3.4, and 3.5.
Python 3.3 and 3.4 are [End-of-life](https://devguide.python.org/#status-of-python-branches).

**Comment by smaeda-ks** [comment]
Thanks for flagging it. We will look into this.

**Comment by smaeda-ks** [comment]
See: https://github.com/twitterdev/twitter-python-ads-sdk/pull/194

Closing.
