### ISSUE TITLE
Active Entities

### ISSUE THREAD

**Issue by ninjas448** [twitterdev/twitter-python-ads-sdk#190]
LineItem.active_entities throws me error "str object has no attribute id" .

**Comment by smaeda-ks** [comment]
Hi @ninjas448 ,

Can you provide us your code example? Or, are you just following the example code here?
https://github.com/twitterdev/twitter-python-ads-sdk/blob/master/examples/active_entities.py

**Comment by juanshishido** [comment]
Is this the error you're seeing, @ninjas448?

```
>>> LineItem.active_entities('18ce54d4x5t', start_time, end_time)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/twitter-python-ads-sdk/twitter_ads/resource.py", line 330, in active_entities
    resource = klass.RESOURCE_ACTIVE_ENTITIES.format(account_id=account.id)
AttributeError: 'str' object has no attribute 'id'
```

If so, then you're seeing the error because you're passing in your account ID into the `active_entities` method (as I've done in the example).

Instead, you'll want to pass in an `Account` object. You can instantiate in the following way.

```
>>> account = client.accounts('18ce54d4x5t')
```

**Comment by ninjas448** [comment]
Thanks a lot ..solved!
