### ISSUE TITLE
Time to wait for async_stats_job_result results

### ISSUE THREAD

**Issue by shaun10** [twitterdev/twitter-python-ads-sdk#201]
I am noticing 15 seconds is sometimes not enough. Should this be increased or a while loop maybe added that continuously waits 15 seconds if there is no result?

**Comment by smaeda-ks** [comment]
@shaun10 Yes, I'd say the later approach is more appropriate in this case. Since this is not an "issue" I'm closing this. If you have a question around SDK usage please ask it through our developer forum instead - under the "Ads API SDKs" category.
https://twittercommunity.com/c/advertiser-api/sdks
