### ISSUE TITLE
Metrics for Paused and Deleted Tweets - active_entities 

### ISSUE THREAD

**Issue by shaun10** [twitterdev/twitter-python-ads-sdk#206]
Can active_entities take with_deleted = true?

https://twittercommunity.com/t/metrics-for-paused-and-deleted-tweets-active-entities/128179

If so will that then result in including paused and deleted tweets? How can we pass it to this method? Just as a dictionary with? - 

`{'with_deleted' : True}` Will that work?

**Comment by smaeda-ks** [comment]
@shaun10 Answered in https://twittercommunity.com/t/metrics-for-paused-and-deleted-tweets-active-entities/128179

I'm closing this as this is not an issue.
