### ISSUE TITLE
Analytics Handle More Than 20 Ids

### ISSUE THREAD

**Issue by mofa** [twitterdev/twitter-python-ads-sdk#208]
Are there any plans to create a batch function to read more than 20 Ids?

**Comment by smaeda-ks** [comment]
@mofa Not at the moment. Could you elaborate a bit more about the "batch function" you mentioned? Are you asking something SDK-only functionality or completely new Ads API endpoint?

**Comment by mofa** [comment]
Hi @smaeda-ks in the Twitter Ads API you have a limit of 20 entity ids per call. Analytics.py example only accounts for 10 Line Items. Do you have an example that handles the batching for you, to get each 20 Ids and then moves on to the next 20 etc..

**Comment by smaeda-ks** [comment]
@mofa It's just basic for-loop. Of course, you can do something like this:

```py
# Note: import `izip_longest` instead if you're on Python 2.x
from itertools import zip_longest

# load 100 items
line_items = list(account.line_items(None, count=100))[:100]
line_item_ids = map(lambda x: x.id, line_items)

queued_job_list = []

# process every 20 ids in list
for group in zip_longest(*[iter(line_item_ids)] * 20):
    data = LineItem.queue_async_stats_job(account, ids, metric_groups)
    queued_job_list.append(data['id'])

print(queued_job_list)
```

**Comment by smaeda-ks** [comment]
Hey @mofa ,
I'm closing this issue for now but let us know if you still have a question regarding this.

Thanks
