### ISSUE TITLE
analytics.py example error

### ISSUE THREAD

**Issue by mofa** [twitterdev/twitter-python-ads-sdk#209]
I am getting the below error when running the analytics.py example:

twitter_ads.error.BadRequest: <BadRequest object at 0x3ba5888 code=400 details=[{'code': 'INVALID_PARAMETER', 'message': 'A minimum of 1 items must be provided for entity_ids', 'parameter': 'entity_ids'}]>

I added a print to make sure that I am getting Ids as in the below and I do get Ids.

ids = map(lambda x: x.id, line_items)
print(list(ids))

Can you please advise?

**Comment by smaeda-ks** [comment]
@mofa Please provide us your code snippet not just those lines but including all related lines.

**Comment by mofa** [comment]
Hi @smaeda-ks , I am referring to those script https://github.com/twitterdev/twitter-python-ads-sdk/blob/master/examples/analytics.py

All I did is put my own credentials without modifying anything in the script and got the below error:

Traceback (most recent call last):
  File "C:.....\analytics.py", line 41, in <module>
    LineItem.all_stats(account, ids, metric_groups)
  File "C:....\AppData\Local\Continuum\anaconda3\lib\site-packages\twitter_ads\resource.py", line 269, in all_stats
    response = Request(account.client, 'get', resource, params=params).perform()
  File "C:.....\AppData\Local\Continuum\anaconda3\lib\site-packages\twitter_ads\http.py", line 69, in perform
    raise Error.from_response(response)
twitter_ads.error.BadRequest: <BadRequest object at 0x3ba97c8 code=400 details=[{'code': 'INVALID_PARAMETER', 'message': 'A minimum of 1 items must be provided for entity_ids', 'parameter': 'entity_ids'}]>

**Comment by smaeda-ks** [comment]
@mofa What's your output of `print(ids)`?

**Comment by mofa** [comment]
I got a list of 10 Ids in the format ['xxxx', 'xxxx'....'xxxx']

**Comment by smaeda-ks** [comment]
@mofa Ok, so that's likely our example code wasn't well tested on Python 3. `map()` returns an iterator object since Python 3 (it used to return a list in Python 2).

You should change:

 ```diff
- ids = map(lambda x: x.id, line_items)
+ ids = list(map(lambda x: x.id, line_items))
LineItem.all_stats(account, ids, metric_groups)
```

I will update the example code later, thanks for raising this.

**Comment by smaeda-ks** [comment]
We've updated the example script. Thanks for reporting this.

Closing
