### ISSUE TITLE
Tweet.create Error occurred in sandbox env

### ISSUE THREAD

**Issue by AndersonYangOh** [twitterdev/twitter-python-ads-sdk#216]
!!!work fine in product env
i am trying to create tweet use sdk `Tweet.create` in sandbox env but Error occurred:
```
client = Client(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET)

client.sandbox = True

# load up the account instance, campaign and line item
account = client.accounts(ACCOUNT_ID)

# create request for a simple nullcasted tweet
tweet1 = Tweet.create(account, text='There can be only one...')
print(tweet1)
```
err log bellow:
```
{
	'errors': [{
		'code': 'METHOD_NOT_ALLOWED',
		'message': 'Method POST not allowed.'
	}],
	'request': {
		'params': {}
	}
}
```

**Comment by smaeda-ks** [comment]
@AndersonYangOh 
Unfortunately, you can't create a tweet using the sandbox environment at the moment. We found a bug and disabled this functionality for the sandbox. We have a plan to fix it but I don't know ETA for this.

**Comment by smaeda-ks** [comment]
Closing this ticket for now as I gave my answer above. Please reopen this if you have any other questions regarding this. Thanks

**Comment by nielsvandermolen** [comment]
Hi, any update on the ETA and general plans to provide support for the sandbox environment?

Is there a list of supported / unsupported API endpoints for the sandbox environment?

A working sandbox environment would be very helpful for automated testing and development.
