### ISSUE TITLE
TypeError: async_stats_job_result() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by mcoirad-gmmb** [twitterdev/twitter-python-ads-sdk#229]
When I run

```
job_status = LineItem.async_stats_job_result(account, job_id)
```
In the analytics.py example, I get:

**TypeError: async_stats_job_result() takes 2 positional arguments but 3 were given**

it seems the function does not accept both arguments. It works when you pass it only the account variable, though, but without the job I'm not sure whats being returned.

**Comment by mcoirad-gmmb** [comment]
Thank you! I made a PR for the example.

**Comment by smaeda-ks** [comment]
@mcoirad-gmmb Right, we need to update the example. Feel free to open a new PR so we can merge it. Thanks
