### ISSUE TITLE
VideoConverstionCard entity class missing name property available in API

### ISSUE THREAD

**Issue by shaun10** [twitterdev/twitter-python-ads-sdk#230]
Just wondering why name hasn't been added for video conversion cards? Should I add it in with a PR? It looks like it is available per the docs. 

https://github.com/twitterdev/twitter-python-ads-sdk/blob/master/twitter_ads/creative.py#L288

https://developer.twitter.com/en/docs/ads/creatives/api-reference/video-conversation

**Comment by shaun10** [comment]
Fixed with #231

**Comment by smaeda-ks** [comment]
The PR is merged, thanks for your help! Closing
