### ISSUE TITLE
LineItem has no attribute "currency".

### ISSUE THREAD

**Issue by dvainrub** [twitterdev/twitter-python-ads-sdk#239]
The `LineItem` object is missing the `"currency"` attribute, 
as you can see on the [Twitter API](https://developer.twitter.com/en/docs/ads/campaign-management/api-reference/line-items).
`"currency"` is one of the fields returned by the 'line_items' request.

I think the fix should be to add the following line of code on file 'campaign.py', line 296:
`resource_property(LineItem, 'currency')`

**Comment by smaeda-ks** [comment]
Thanks! https://github.com/twitterdev/twitter-python-ads-sdk/pull/244
