### ISSUE TITLE
Account has no attribute "business_name" nor "business_id"

### ISSUE THREAD

**Issue by dvainrub** [twitterdev/twitter-python-ads-sdk#241]
The `Account` object is missing the `"business_name"` and `"business_id"` attribute,
as you can see on the [Twitter API](https://developer.twitter.com/en/docs/ads/campaign-management/api-reference/accounts).
"business_name" and "business_id" are fields returned by the 'accounts' request.

I think the fix should be to add the following line of code on file `'account.py'`, line 186:
`resource_property(Account, 'business_id')`
`resource_property(Account, 'business_name')`

**Comment by smaeda-ks** [comment]
Thanks! https://github.com/twitterdev/twitter-python-ads-sdk/pull/244
