### ISSUE TITLE
Remove deprecated sentiment targeting

### ISSUE THREAD

**Issue by osowskit** [twitterdev/twitter-python-ads-sdk#246]
Per [this announcement](https://twittercommunity.com/t/announcement-sentiment-targeting-for-line-items-deprecation/132689/4):

> As of January 21st 2020, sentiment targeting on line items will no longer be supported via the Twitter Ads API.

This should be removed from the line item options:

https://github.com/twitterdev/twitter-python-ads-sdk/blob/6e2da7aa161b99a8ca4b3759e3a997119db2c8e0/twitter_ads/campaign.py#L298

**Comment by tushdante** [comment]
Thanks for calling this out!
