### ISSUE TITLE
Got 403 FORBIDDEN error when getting media_library = MediaLibrary.all(account) 

### ISSUE THREAD

**Issue by BJapac** [twitterdev/twitter-python-ads-sdk#271]
There is an issue causing 403 FORBIDDEN error when using media_library = MediaLibrary.all(account)  to retrieve media library details.
This can happen when using code such as: line_item =LineItem.all(account) or if you use campaign = Campaign.all(account) to get lineItem and campaign, and it's working fine.

**Comment by tushdante** [comment]
On investigation this is likely a permissions issue given that the following works fine `MediaLibrary.all(account)`
