### ISSUE TITLE
 Class ImageAppDownloadCard  Attribution Error

### ISSUE THREAD

**Issue by keame** [twitterdev/twitter-python-ads-sdk#274]
### **The following error occurred when I created the card.**
![image](https://user-images.githubusercontent.com/70134900/109247959-d94db580-781f-11eb-8e80-9f43b5505d8e.png)

**Comment by andypiper** [comment]
Is that a typo in the card info? googlepaly vs googleplay? would that have any effect on your code?

**Comment by keame** [comment]
The problem has already been solved。
