### ISSUE TITLE
API v10

### ISSUE THREAD

**Issue by Hugo4400** [twitterdev/twitter-python-ads-sdk#285]
Hello,

I've noticed via [this tweet](https://twitter.com/AdsAPI/status/1432809296836759552) that ads API v10 was out.
However, it hasn't been added to the [official documentation](https://developer.twitter.com/en/docs/twitter-ads-api/versioning), even though v9 is depreciated.

I was wondering if you had a timeframe for when the SDK would support v10 ?

**Comment by tushdante** [comment]
Thanks for flagging! The updated to v10 has been completed as part of #288
