### ISSUE TITLE
error forbidden

### ISSUE THREAD

**Issue by johendry** [twitterdev/twitter-python-ads-sdk#47]
i try run the script by python, but its got error forbidden?
what should i do ? anyone can help me?

**Comment by brandonblack** [comment]
Hello @johendry. Forbidden (403) responses occur when you don't have permission to access a given resource or when your application isn't yet white-listed to access the Twitter Ads API. The API is still part of a closed partner program at the moment but you can apply for access [here](https://dev.twitter.com/ads/overview) and our BD team will process your application.

If you have any additional questions about the partner program, you may get answers quicker over in the [Twitter developer forums](https://twittercommunity.com/c/advertiser-api). If you have additional questions about the SDK itself please feel free to open another question ticket here or you can also ask about it in the forums.

**Comment by johendry** [comment]
hello @brandonblack, now i try use twython library to get data, and now get error like this
Twitter API returned a 401 (Unauthorized), This request is not properly authenticated 

can you help me to solve it?
