### ISSUE TITLE
analytics.py example returns internal server error

### ISSUE THREAD

**Issue by eyal13579** [twitterdev/twitter-python-ads-sdk#69]
after filling all the required params, and refer it to the sandbox (**kwargs) - I get 500

> $ python analytics.py 
> Traceback (most recent call last):
>   File "analytics.py", line 53, in <module>
>     async_stats_job_result = LineItem.async_stats_job_result(account, job_id)
>   File "/usr/lib/python2.7/site-packages/twitter_ads/resource.py", line 247, in async_stats_job_result
>     response = Request(account.client, 'get', resource, params=params).perform()
>   File "/usr/lib/python2.7/site-packages/twitter_ads/http.py", line 75, in perform
>     raise Error.from_response(response)
> twitter_ads.error.ServerError: <ServerError object at 0x279e500 code=500 details=[{u'message': u'Internal Error'
> , u'code': u'INTERNAL_ERROR'}]>

**Comment by tushdante** [comment]
@eyal13579 I haven't been able to reproduce your issue. I've been able to run the `analytics.py` script using the sandbox just fine. Can you please send us the exact steps to replicate this issue?

**Comment by tushdante** [comment]
Closing this out, CANNOT REPRO
