### ISSUE TITLE
Reference documentation static assets don't load.

### ISSUE THREAD

**Issue by frewsxcv** [twitterdev/twitter-python-ads-sdk#73]
http://twitterdev.github.io/twitter-python-ads-sdk/reference/index.html

![screen shot 2016-07-07 at 12 26 10 pm](https://cloud.githubusercontent.com/assets/416575/16660818/02e5173c-443e-11e6-839e-8847f6bea6b8.png)

**Comment by smaeda-ks** [comment]
https://twitterdev.github.io/twitter-python-ads-sdk/

Closing this.
